services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jvict -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: jvict
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_network
    secrets:
      - postgres_pass
    restart: unless-stopped

  finance-api:
    build:
      context: .
    image: finance-api:v0.0.4a
    container_name: finance_api_container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE: postgres
      DATABASE_ENDPOINT: postgres
      DATABASE_USERNAME: jvict
      DATABASE_PASSWORD: /run/secrets/postgres_pass
      DATABASE_PORT: 5432
      SECRET_KEY: /run/secrets/secret_key
      ADMIN_PASSWORD: /run/secrets/admin_password
      ADMIN_USERNAME: jvict
      ADMIN_EMAIL: admin@example.com
      ADMIN_FULL_NAME: Admin User
    ports:
      - "8000:8000"
    networks:
      - finance_network
    secrets:
      - postgres_pass
      - secret_key
      - admin_password

volumes:
  postgres_data:

networks:
  finance_network:
    driver: bridge

secrets:
  postgres_pass:
    file: ./sql/secrets/user_credentials.txt
  secret_key:
    file: ./secrets/secret_key.txt
  admin_password:
    file: ./secrets/admin_password.txt